import test from 'node:test';
import assert from 'node:assert/strict';
import { summarizeInbox } from './assistant.mjs';
import { toolName } from './session.mjs';

function fixture({ args = '{}', data = { messages: [{ id: 'private-id', subject: 'Release review', snippet: 'Review at 14:00 UTC.' }] }, extraTool = false } = {}) {
  const requests = [], events = [];
  let calls = 0;
  const client = {
    async listTools() { return { tools: [{ name: toolName }, ...(extraTool ? [{ name: 'unexpected' }] : [])] }; },
    async callTool(call) {
      calls++;
      assert.deepEqual(call, { name: toolName, arguments: {} });
      return { structuredContent: data };
    }
  };
  const requestModel = async body => {
    requests.push(structuredClone(body));
    return requests.length === 1
      ? { status: 'completed', output: [{ type: 'function_call', call_id: 'test-call', name: 'read_inbox', arguments: args }] }
      : { status: 'completed', output: [{ type: 'message', content: [{ type: 'output_text', text: 'Fixture summary; not generated by a live model.' }] }] };
  };
  return { client, requestModel, question: 'Summarize my inbox.', trace: event => events.push(event), requests, events, callCount: () => calls };
}

test('passes only subjects/snippets as tool output and logs only bounded metadata', async () => {
  const f = fixture();
  await summarizeInbox(f);
  assert.equal(f.callCount(), 1);
  assert.equal(f.requests.length, 2);
  const result = f.requests[1].input.at(-1);
  assert.equal(result.type, 'function_call_output');
  assert.deepEqual(JSON.parse(result.output), { messages: [{ subject: 'Release review', snippet: 'Review at 14:00 UTC.' }] });
  assert.deepEqual(f.requests[1].tools, []);
  assert.deepEqual(f.events, [{ tool: 'read_inbox', arguments: {} }, { message_count: 1 }]);
});

test('rejects model-supplied endpoints before invoking Gmail', async () => {
  const f = fixture({ args: '{"endpoint":"/gmail/v1/users/me/messages"}' });
  await assert.rejects(summarizeInbox(f));
  assert.equal(f.callCount(), 0);
});

test('rejects unexpected fields and oversized text before the summary request', async () => {
  for (const record of [
    { id: 'id', subject: 'subject', snippet: 'text', access_token: 'fixture-only' },
    { id: 'id', subject: 'subject', snippet: 'x'.repeat(501) }
  ]) {
    const f = fixture({ data: { messages: [record] } });
    await assert.rejects(summarizeInbox(f));
    assert.equal(f.requests.length, 1);
  }
});

test('rejects unexpected tool discovery before contacting the model', async () => {
  const f = fixture({ extraTool: true });
  await assert.rejects(summarizeInbox(f));
  assert.equal(f.requests.length, 0);
});

test('passes an empty inbox explicitly without inventing messages', async () => {
  const f = fixture({ data: { messages: [] } });
  await summarizeInbox(f);
  assert.deepEqual(JSON.parse(f.requests[1].input.at(-1).output), { messages: [] });
});
